### PR TITLE
Retry add_certificate_chain_file changes

### PR DESCRIPTION
**Pull request by hsbt**
/cc @ioquatix 

This reverts commit 23b07043e7fde743ff920f8354b5a094fee19a03.

Fixes https://github.com/ruby/openssl/issues/318

### CODE REVIEW

**Comment by hsbt** [comment]
It's good to reproduce test fails same as ruby repo at https://github.com/ruby/openssl/pull/325/checks?check_run_id=448254316

**Comment by ioquatix** [comment]
I’m not sure why we reverted this on master and then made a pr to revert that. Was it just to show test failures?

**Comment by ioquatix** [comment]
It’s a little bit risky to revert a change on master because people are using master branch with new features...

**Comment by hsbt** [comment]
>I’m not sure why we reverted this on master and then made a pr to revert that. Was it just to show test failures?

@ioquatix Yes. This pr is a working branch for the new feature.

We can fix this branch with mswin platform if we hope to add the `add_certificate_chain_file` with the private key file feature.

**Comment by rhenium** [comment]
Closing in favor of #441 (merged last year).

**Pull request closed without merging**
