### PR TITLE
move ractor safe macro to ossl.h

### PR DESCRIPTION
**Pull request by HoneyryderChuck**
as requested [here](https://github.com/ruby/openssl/pull/808#issuecomment-2444193790)

### CODE REVIEW

**Comment by HoneyryderChuck** [comment]
@rhenium the suggested macro makes the build fail for those two windows builds. not sure whether it's better to keep the original macro.

**Comment by rhenium** [comment]
The failure with `windows-latest 3.2` and 3.3 is irrelevant. It's failing with master, too (https://github.com/ruby/openssl/issues/812).

Could you update the commit message to include some more context? Also, "openssl.h" → "ossl.h".

**Comment by HoneyryderChuck** [comment]
done

**Comment by rhenium** [comment]
Thank you!

**Pull request merged**
