### PR TITLE
Sync extconf.rb with ruby/ruby

### PR DESCRIPTION
**Pull request by peterzhu2118**
Adds commit ruby/ruby@6d8f396f37350b7aa9c85a097929f54a0939448b and
ruby/ruby@c8b3bd45cc3cae93ae701333202416838ee6a00c.

### CODE REVIEW

**Comment by nobu** [comment]
This is kept un-backported intentionally, so that these warnings will be fixed.

**Comment by nobu** [comment]
I changed my mind.
It seems tough to “fix” warnings, until we drop the support for older OpenSSLs.
However since the current way is too compiler dependent, how about this?
https://github.com/nobu/openssl/tree/openssl3-warnings

**Comment by peterzhu2118** [comment]
I think that looks good. But we should still sync the `extconf.rb` between the ruby/openssl and ruby/ruby right?

**Comment by nobu** [comment]
ruby/ruby@6d8f396 will be reverted and sync from here to ruby/ruby, in that case.

**Comment by hsbt** [comment]
What's the next action? I'm not sure we choose https://github.com/nobu/openssl/commit/ee5347a99cc6576474be606cc5ab2b15b44819cb instead of this pull-request.

**Comment by hsbt** [comment]
https://github.com/ruby/openssl/pull/576 is best way for this.

**Pull request closed without merging**
