### PR TITLE
asn1: handle GENERALIZEDTIME without seconds

### PR DESCRIPTION
**Pull request by yogo1212**
encountered this error using a certificate that is accepted by other clients:
```
OpenSSL::X509::Certificate.new File.read ("openssl_test.crt")
TypeError: bad GENERALIZEDTIME format
```
this is from asn1parse:
```
  147:d=2  hl=2 l=  30 cons:   SEQUENCE          
  149:d=3  hl=2 l=  13 prim:    GENERALIZEDTIME   :201401010000Z
  164:d=3  hl=2 l=  13 prim:    UTCTIME           :390512144609Z
```

### CODE REVIEW

**Comment by rhenium** [comment]
Thanks for the PR!

Indeed, X.680 specifies that the seconds part can be absent. The asn1time_to_time() function also does not handle {UTC,Generalized}Time with fraction seconds or time zones, but this would be out of scope of this PR.

Could you add some basic tests to test/test_asn1.rb, and update the commit message to include the rationale about the change before merge?

**Comment by yogo1212** [comment]
@rhenium ping :-)

**Comment by rhenium** [comment]
@yogo1212 Nice, thanks! Could you squash the third commit into the first one?

**Comment by yogo1212** [comment]
nothing comes more naturally than changing the course of history in the past :-D

**Comment by rhenium** [comment]
Thanks!

**Pull request merged**
