### PR TITLE
Support SHA-3 hash functions 

### PR DESCRIPTION
**Pull request by yuan-xy**
add SHA3_224, SHA3_256, SHA3_384 and SHA3_512 class under OpenSSL::Digest module.

### CODE REVIEW

**Comment by ioquatix** [comment]
I wonder if we can use something better than class name. e.g. constant.

**Comment by ioquatix** [comment]
Maybe have `SHA3_224::NAME = "SHA3-224"`. What do you think?

**Comment by yuanxinyu** [comment]
> Maybe have `SHA3_224::NAME = "SHA3-224"`. What do you think?

Maybe it works,  but I can't figure out how to implements this.  In addtion, there is a 'name' method there:
`rb_define_method(cDigest, "name", ossl_digest_name, 0);`

**Comment by ioquatix** [comment]
Can this help you?

https://silverhammermba.github.io/emberb/c/#constants-1

**Comment by yuanxinyu** [comment]
how about this,
`	if(strncmp(name, "SHA3_", 5) && strlen(name)==9) {
		char n_name[9];
		strncpy(n_name, name, 9);
		n_name[4] = '-';
		md = EVP_get_digestbyname(n_name);
`
which is better than original code
`
    char *pos = strchr(name, '_');
	if(pos) {
		char n_name[9];
		char *n_pos;
		strncpy(n_name, name, 9);
		n_pos = strchr(n_name, '_');
		*n_pos = '-';
		md = EVP_get_digestbyname(n_name);
`

**Comment by yuanxinyu** [comment]
how about this,

> 	if(strncmp(name, "SHA3_", 5) && strlen(name)==9) {
		char n_name[9];
		strncpy(n_name, name, 9);
		n_name[4] = '-';
		md = EVP_get_digestbyname(n_name);

which is better than original code

>     char *pos = strchr(name, '_');
	if(pos) {
		char n_name[9];
		char *n_pos;
		strncpy(n_name, name, 9);
		n_pos = strchr(n_name, '_');
		*n_pos = '-';
		md = EVP_get_digestbyname(n_name);

**Comment by yuanxinyu** [comment]
how about this code:
> if(strcmp(name, "SHA3_224") {
>       md = EVP_get_digestbyname("SHA3-224");
> else if(strcmp(name, "SHA3_256") {
>       md = EVP_get_digestbyname("SHA3-256");
> else if(strcmp(name, "SHA3_384") {
>       md = EVP_get_digestbyname("SHA3-384");
> else if(strcmp(name, "SHA3_512") {
>       md = EVP_get_digestbyname("SHA3-512");
> }

**Comment by ioquatix** [comment]
I still think using constant is better, @mame what do you think?

**Comment by yuan-xy** [comment]
Maybe someone else can help support SHA-3 hash functions in ruby.

**Comment by ioquatix** [comment]
So, for each class, you need to write something like:

```
rb_define_const(digest_class, "NAME", "SHA3-384");
```

Then, in the method to create it, you need to use:

```
rb_const_get_at(digest_class, rb_intern("NAME"));
```

Does that make sense?

**Comment by ioquatix** [comment]
@yuan-xy you are very close to having a workable solution. Let me know if you'd like to finish this off.

**Comment by yuan-xy** [comment]
I’m on a long vacation, I will figure out how to finish it after vacation.

在 2019年9月28日，05:29，Samuel Williams <notifications@github.com<mailto:notifications@github.com>> 写道：


@yuan-xy<https://github.com/yuan-xy> you are very close to having a workable solution. Let me know if you'd like to finish this off.

**Comment by yuan-xy** [comment]
After many attempts, I still don't know how to implement it use `rb_define_const`.  
The digest class has not initialized when `ossl_evp_get_digestbyname` being called. How to define this:
```
 rb_define_const(digest_class, "NAME", "SHA3-384");
```

**Pull request closed without merging**
