### PR TITLE
Appveyor status badge

### PR DESCRIPTION
**Pull request by hsbt**
Added appveyor status by status badge

### CODE REVIEW

**Comment by rhenium** [comment]
I personally don't like status badges because they work poorly on non-default (non-master) branches. Isn't the ✓ mark in the commit log[1] enough?

[1]: https://github.com/ruby/openssl/commits/master

**Comment by hsbt** [comment]
I partly agreed your comment. 3rd-party build statues are fragile in a lot of cases.

But I always use status badge for actively of repository/software. It's not for maintainers, It's for users who interested in this project.

**Comment by hsbt** [comment]
I understood details of `they work poorly on non-default (non-master) branches.` 

We need to point-out build status of stable branches used GitHub API.

**Comment by rhenium** [comment]
While this is not a good way, I can also imagine that people use the badges as an indicator that the project is actively maintained. For this purpose, it is ok if master shows the correct status.

**Pull request merged**
