### PR TITLE
Automate processes for ruby-openssl-docker.

### PR DESCRIPTION
**Pull request by junaruga**
This is related to https://github.com/ruby/openssl/issues/224 suggestion 3, automation.

### CODE REVIEW

**Comment by ioquatix** [comment]
Is this still relevant?

Do you think we should do both or try to move to GitHub Actions?

**Comment by junaruga** [comment]
Right now following `Dockerfile` is used in `.travis.yml`, 
https://github.com/ruby/openssl/blob/master/Dockerfile

The `Dockerfile` is downloading the image from following DockerHub repository.
https://hub.docker.com/r/zzak/ruby-openssl-docker/tags

When I sent this pull-request, the image was created from following `Dockerfile`, building and pushing manually.
https://github.com/ruby/openssl/blob/master/tool/ruby-openssl-docker/Dockerfile

So, if this project still doing it manually, it is relevant.
But if this project have a plan to automate the building and pushing the image somewhere GitHub Actions or etc, this PR is not relevant.

By the way, this repository's `.trafvis.yml` is still `dist: trusy`, we can update it `dist: xenial` or dist: bionic`. After that, we do not have to install docker-compose manually.

**Comment by ioquatix** [comment]
> By the way, this repository's .trafvis.yml is still dist: trusy, we can update it dist: xenial or dist: bionic`. After that, we do not have to install docker-compose manually.

Can you make a PR?

**Comment by junaruga** [comment]
> Can you make a PR?

Sure. I sent the PR https://github.com/ruby/openssl/pull/283 .

**Comment by junaruga** [comment]
Now I am rebasing this PR on the latest master branch.

Let me explain the logic in the PR.

First, you will see 3 stages (= 3 steps).

```
stages:
  - prepare
  - test
  - deploy
```
`prepare` and `deploy` stages are new. `test` is current one.


## 1. `prepare` stage

Check the files in the commits of the PR, then if following files are included in the commit, set `BUILD_RUBY_OPENSSL_DOCKER` flag as `true`.

```
tool/ruby-openssl-docker/Dockerfile
tool/ruby-openssl-docker/init.sh
```

Then push the built image to `$IMAGE:pr` on DockerHub by `docker push $IMAGE:pr`. `$IMAGE:pr` is a kind of temporary image used during the PR.
Because there is no way to use image across each Travis job.

## 2. `test` stage

If `BUILD_RUBY_OPENSSL_DOCKER` flag is `true`. use the `$IMAGE:pr` image for testing replacing image URL in `Dockerfile` by `sed` command. (script part in `.travis.yml`)

## 3. `deploy` stage

If `BUILD_RUBY_OPENSSL_DOCKER` flag is `true`, set `$IMAGE:pr` as `$IMAGE:testing` by `docker tag $IMAGE:pr $IMAGE:testing`, and push the image.

## Notes

I expect `$DOCKER_USER` as `zzak` (current setting), But you can use other DockerHub account. because `zzak` looks a person's account, not organization's account.

**Comment by junaruga** [comment]
> Do you think we should do both or try to move to GitHub Actions?

I do not think the feature of PR needs for both Travis CI and GitHub Actions, because this PR is to verify, build and push the testing image.

I am not sure if we move to GitHub Actions.
Seeing current `.github/workflows/workflow.yml` file, it seems there is no test with docker-compose command and with supported openssl dependencies.

**Comment by ioquatix** [comment]
Yes, you are correct, there is no docker in GitHub Actions.

The point of docker is to make it easy to build isolated versions of OpenSSL, LibraSSL and Ruby, right?

Forgive me but I don't use docker much. Does it build a new image? Why do we need to refer to some users account in order to use the image? Is it cached?

**Comment by junaruga** [comment]
> The point of docker is to make it easy to build isolated versions of OpenSSL, LibraSSL and Ruby, right?

Yes, right. Look at this https://github.com/ruby/openssl/blob/master/tool/ruby-openssl-docker/Dockerfile#L3-L9 .
The `Dockerfile` used as the base image is covering all the supported OpenSSL and LibraSSL and Rubies except Ruby 2.6. This image is for a kind of acceptance test that GitHub Actions and Travis CI host environment do not cover.

> Forgive me but I don't use docker much. Does it build a new image? Why do we need to refer to some users account in order to use the image? Is it cached?

Of course I am happy to answer your question.
Yes this PR builds a new image `$DOCKER_USER/ruby-openssl-docker:pr` that is a kind of working image that is used during a pull-request. Because it is used across the jobs in a build of the pull-request.

> Why do we need to refer to some users account in order to use the image?

I intended `$DOCKER_USER` and `$DOCKER_PASSWORD` are set on Travis Setting page like this.

https://github.com/multiarch/qemu-user-static/blob/master/docs/images/forked-repo-travis-ci-settings.png

Because the used `zzak` account is a personal account. I thought you might prefer to use organization account of DockerHub in this timing instead of this timing. But I think I had a mistake. Using 2 accounts at the same timing is wrong. Do you like adding `$DOCKER_USER` = `zzak` in `.travis.yml` like this?

```
$ git diff
diff --git a/.travis.yml b/.travis.yml
index 6eef0d2..60b386b 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -5,6 +5,7 @@ services:
   - docker
 env:
   global:
+    - DOCKER_USER=zzak
     - IMAGE="$DOCKER_USER/ruby-openssl-docker"
 before_install:
   - sudo apt-get -qq update
```

Here is an example of the project I am co-maintainer. You see an organization account "multiarch" is used on DockerHub.
https://github.com/multiarch/qemu-user-static
https://hub.docker.com/r/multiarch/qemu-user-static/

> Is it cached?

Which timing are you talking about?
The image is not cached on local. Because each job's environment is clean.

**Comment by ioquatix** [comment]
I have not forgotten about this issue.

**Comment by junaruga** [comment]
Yeah, thanks for reminding it.
While the automation makes maintainer's work easier, I wish this PR is just for reference, and you do not need to merge this PR. And you can update `.travis.yml` by yourself for a better maintainability.

**Comment by junaruga** [comment]
I see now this project is using Github Actions. 
So, I think this PR is outdated. Feel free to close this PR. :)

**Comment by junaruga** [comment]
I close it by myself for now.

**Pull request closed without merging**
