### PR TITLE
Helper to retrieve CRL URIs from a certificate

### PR DESCRIPTION
**Pull request by bdewater**
Similar to https://github.com/ruby/openssl/pull/260

According to [RFC 5280](https://tools.ietf.org/html/rfc5280#section-4.2.1.13) a distribution point can contain a lot of things, but in practice I'm seeing only `fullName` URIs (`6`).

### CODE REVIEW

**Comment by ioquatix** [comment]
Do you think we should add an example showing how to use it/why to use it?

**Comment by bdewater** [comment]
I guess https://github.com/ruby/openssl/blob/master/sample/crlstore.rb could be updated, but that one in itself isn't terribly clear either 😕 

I was planning to use it myself in https://github.com/cedarcode/webauthn-ruby/pull/208 where I currently have an more brittle and uglier regex match to get the URI.

**Comment by ioquatix** [comment]
For the name of the module, what are your thoughts on the casing, should it be `CRLDistributionPoints` since `CRL` is an abbreviation?

**Comment by bdewater** [comment]
Sounds good to me, updated.

**Comment by bdewater** [comment]
Hum, one flaky test that failed (and I can't restart) but the rest is all green.

**Comment by ioquatix** [comment]
LGTM.

**Pull request merged**
