### PR TITLE
Update the latest version of EnvUtil

### PR DESCRIPTION
**Pull request by hsbt**
Resolve https://github.com/ruby/openssl/pull/589

`envutil.rb` in this repository is pretty old. I update it with the latest version of ruby/ruby repository.

### CODE REVIEW

**Comment by eregon** [comment]
This new version seems to have the same problem as the old one:
From https://github.com/ruby/openssl/actions/runs/3837266200/jobs/6532377487 but on CRuby 3.0:
```
===============================================================================
Error: test_openssl_engine_id_name_inspect(OpenSSL::TestEngine):
  Timeout::Error: execution of assert_separately expired timeout (10 sec)
  pid 6324 killed by SIGKILL (signal 9)
  | 
  | /home/runner/work/openssl/openssl/test/openssl/test_engine.rb:77: warning: Skipping set of ruby2_keywords flag for with_openssl (method accepts keywords or method does not accept argument splat)
-------------------------------------------------------------------------------
0 tests, 1 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
0% passed
-------------------------------------------------------------------------------
0.00 tests/s, 0.02 assertions/s
5 tests, 6 assertions, 0 failures, 5 errors, 0 pendings, 0 omissions, 0 notifications
Finished in 59.363426555 seconds.
-------------------------------------------------------------------------------
6 tests, 6 assertions, 0 failures, 6 errors, 0 pendings, 0 omissions, 0 notifications
-------------------------------------------------------------------------------
0 tests, 1 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
0% passed
-------------------------------------------------------------------------------
0.00 tests/s, 0.03 assertions/s

0% passed
-------------------------------------------------------------------------------
0.06 tests/s, 0.09 assertions/s
Finished in 51.416196363 seconds.

-------------------------------------------------------------------------------
0% passed
-------------------------------------------------------------------------------
0.07 tests/s, 0.09 assertions/s
Finished in 26.780028326 seconds.
-------------------------------------------------------------------------------
1 tests, 2 assertions, 0 failures, 1 errors, 0 pendings, 0 omissions, 0 notifications
0% passed
-------------------------------------------------------------------------------
```

**Comment by eregon** [comment]
https://github.com/ruby/openssl/pull/593/files#diff-e3677884066a26b36e5b40dec61618ca2e3de14232a1468e9989696b7ffdcbf3R251 does `Test::Unit::Runner.class_variable_set(:@@stop_auto_run, true) if defined?(Test::Unit::Runner)` which doesn't seem correct with recent test-unit.

**Comment by hsbt** [comment]
We can remove L251 and L263. But I'm not sure why tests failed with < Ruby 3.1.

**Comment by hsbt** [comment]
@eregon Thanks. I understood https://github.com/ruby/openssl/pull/589 and https://github.com/oracle/truffleruby/issues/2800.

**Review by eregon — APPROVED** [review]
Looks good to me

**Review by rhenium — APPROVED** [review]
Looks good to me. Thank you!

**Pull request merged**
